version: "3.9"

services:
  app:
    build: .
    container_name: python_app
    depends_on:
      - db
    environment:
      - DB_NAME=mydatabase
      - DB_USER=Lavanya
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "5000:5000"   # Change if your app runs on another port
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=Lavanya
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge

